name: Test
on:
  pull_request:
  push:
    branches:    
      - master
      - development

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content # fetch the contents of the repository
        uses: actions/checkout@v2
      - name: Build container
        run: |
          ls
          make build
      - name: Pytest
        run: |
          make test-ci
